---
title: "1 - Specifying your model"
date: 'Last updated: 2019-08-06'
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{1 - Specifying your model}     
  %\VignetteEngine{knitr::rmarkdown} 
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Introduction
The Model Specification Workbook (MSW) is used to specify your model. The MSW is 
a series of two worksheets (CSV files) that describe different model components. 

You can use __cchsflow__ without a MSW but we recommend using the 
`variablesCCHSFlow` and `cchsVariableDetails` worksheets. 

## Two worksheets in the Model Specification Workbook
1) `variablesCCHSFlow` --- all model variables, including data cleaning and transformations. `variablesCCHSFlow` is the most important sheet and is helpful even if you don't use other parts of _cchsflow_ 
2) `cchsVariableDetails` --- information on factors (categories) and how to transform final variables from their starting variables. 

## How to create the Model Specification Workbook
There are two approaches to creating the Model Specification Workbook. We usually start the Model Specification Workbook as a CSV file to facilate collaboration between study colloborators. Alternatively, you can create the MSW as an R dataframe.

## Creating the `cchsVariableDetails` worksheet

## Creating the `variablesCCHSFlow` worksheet

