---
title: "cjph-abstract"
author: "Warsame Yusuf"
date: '2020-03-30'
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Abstract

**Setting:** Open science refers to research that is transparent and publicly accessible. This includes the sharing of literature, data, and code. The Canadian Community Health Survey (CCHS) is a cross-sectional survey with over 130,000 respondents, and is done on an annual or biennial basis. While the survey remains relatively consistent over the years, there are major differences between cycles that requires researchers to spend time cleaning and preparing the datasets, taking time away from data analysis. This projects aims to address the issue of data cleaning and data preparation for the CCHS using open science practices.

**Intervention:** The objectives of this project is to develop a package that transforms & harmonizes CCHS variables across multiple survey cycles, generating a library of variables that can be used for health data research. This package would minimize the amount of time spent cleaning and transforming CCHS datasets for health data research. 

**Outcomes:** The _cchsflow_ R package was developed that uses data from the CCHS Public Use Microdata File (PUMF) for survey cycles between 2001 and 2014. Specification worksheets were created that identify variables, their names in previous cycles, their category structure, and their final variable names. These worksheets were then used to recode variables in each CCHS cycle, creating harmonized datasets that can be easily combined into one labelled dataset for analysis. The package was then added as a GitHub repository to encourage collaboration with other researchers.

**Implication:** The _cchsflow_ package has been added to the Comprehensive R Network; and contains support for over 140 CCHS variables, generating a dataset of over 1 million respondents. Some variables could not be harmonized due to irreconcilable differences, in which either derived variables were created or kept as separate variables. Some variables were not present in all CCHS survey cycles.

**Conclusion:** By implementing open science practices, _cchsflow_ aims to minimize the amount of time needed to clean and prepare CCHS data for the many CCHS users across Canada.